// Code generated by ent, DO NOT EDIT.

package gameitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the gameitem type in the database.
	Label = "game_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCollection holds the string denoting the collection field in the database.
	FieldCollection = "collection"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldRarity holds the string denoting the rarity field in the database.
	FieldRarity = "rarity"
	// EdgeUserItems holds the string denoting the user_items edge name in mutations.
	EdgeUserItems = "user_items"
	// Table holds the table name of the gameitem in the database.
	Table = "game_items"
	// UserItemsTable is the table that holds the user_items relation/edge.
	UserItemsTable = "user_items"
	// UserItemsInverseTable is the table name for the UserItem entity.
	// It exists in this package in order to avoid circular dependency with the "useritem" package.
	UserItemsInverseTable = "user_items"
	// UserItemsColumn is the table column denoting the user_items relation/edge.
	UserItemsColumn = "item_id"
)

// Columns holds all SQL columns for gameitem fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCollection,
	FieldType,
	FieldRarity,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CollectionValidator is a validator for the "collection" field. It is called by the builders before save.
	CollectionValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(int) error
	// RarityValidator is a validator for the "rarity" field. It is called by the builders before save.
	RarityValidator func(int) error
)

// OrderOption defines the ordering options for the GameItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCollection orders the results by the collection field.
func ByCollection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollection, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByRarity orders the results by the rarity field.
func ByRarity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRarity, opts...).ToFunc()
}

// ByUserItemsCount orders the results by user_items count.
func ByUserItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserItemsStep(), opts...)
	}
}

// ByUserItems orders the results by user_items terms.
func ByUserItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserItemsTable, UserItemsColumn),
	)
}
