services:
  websocket-api-gateway:
    container_name:
      websocket-api-gateway
    build:
      context: .
      dockerfile: ./deployments/docker/websocket.Dockerfile
    ports:
      - "127.0.0.1:8090:8090"
      - "127.0.0.1:50051:50051"
      - "127.0.0.1:50052:50052"
    environment:
      - MAIN_GRPC_PORT=${WEBSOCKET_MAIN_GRPC_PORT:-50051}
      - DRAFT_GRPC_PORT=${WEBSOCKET_DRAFT_GRPC_PORT:-50052}
      - HTTP_PORT=${WEBSOCKET_HTTP_PORT:-8090}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - ENV_TYPE=${ENV_TYPE:-dev}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/ping" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 15s
    networks:
      monitoring:

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - websocket-api-gateway
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
