// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FriendRequestsColumns holds the columns for the "friend_requests" table.
	FriendRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "from_user_id", Type: field.TypeInt},
		{Name: "to_user_id", Type: field.TypeInt},
	}
	// FriendRequestsTable holds the schema information for the "friend_requests" table.
	FriendRequestsTable = &schema.Table{
		Name:       "friend_requests",
		Columns:    FriendRequestsColumns,
		PrimaryKey: []*schema.Column{FriendRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "friend_requests_users_sent_friend_requests",
				Columns:    []*schema.Column{FriendRequestsColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "friend_requests_users_received_friend_requests",
				Columns:    []*schema.Column{FriendRequestsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// GameItemsColumns holds the columns for the "game_items" table.
	GameItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "collection", Type: field.TypeString},
		{Name: "type", Type: field.TypeInt},
		{Name: "rarity", Type: field.TypeInt},
	}
	// GameItemsTable holds the schema information for the "game_items" table.
	GameItemsTable = &schema.Table{
		Name:       "game_items",
		Columns:    GameItemsColumns,
		PrimaryKey: []*schema.Column{GameItemsColumns[0]},
	}
	// MatchesColumns holds the columns for the "matches" table.
	MatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "player1_penalty_time", Type: field.TypeInt, Default: 0},
		{Name: "player2_penalty_time", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"characters_reveal", "waiting_for_ready", "drafting", "matching", "finished"}, Default: "characters_reveal"},
		{Name: "result", Type: field.TypeEnum, Nullable: true, Enums: []string{"player1_win", "player2_win", "draw"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "changed_to_current_status_at", Type: field.TypeTime},
		{Name: "player1_id", Type: field.TypeInt},
		{Name: "player2_id", Type: field.TypeInt},
	}
	// MatchesTable holds the schema information for the "matches" table.
	MatchesTable = &schema.Table{
		Name:       "matches",
		Columns:    MatchesColumns,
		PrimaryKey: []*schema.Column{MatchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "matches_users_player1",
				Columns:    []*schema.Column{MatchesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "matches_users_player2",
				Columns:    []*schema.Column{MatchesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MatchResultsColumns holds the columns for the "match_results" table.
	MatchResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "value", Type: field.TypeInt},
		{Name: "is_retry", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "match_id", Type: field.TypeInt},
		{Name: "player_id", Type: field.TypeInt},
	}
	// MatchResultsTable holds the schema information for the "match_results" table.
	MatchResultsTable = &schema.Table{
		Name:       "match_results",
		Columns:    MatchResultsColumns,
		PrimaryKey: []*schema.Column{MatchResultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "match_results_matches_results",
				Columns:    []*schema.Column{MatchResultsColumns[4]},
				RefColumns: []*schema.Column{MatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "match_results_users_user",
				Columns:    []*schema.Column{MatchResultsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// StatisticsColumns holds the columns for the "statistics" table.
	StatisticsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"global"}, Default: "global"},
		{Name: "period", Type: field.TypeInt, Default: 0},
		{Name: "xp", Type: field.TypeInt, Default: 0},
		{Name: "match_count", Type: field.TypeInt, Default: 0},
		{Name: "wins_count", Type: field.TypeInt, Default: 0},
		{Name: "loses_count", Type: field.TypeInt, Default: 0},
		{Name: "draws_count", Type: field.TypeInt, Default: 0},
		{Name: "result_time", Type: field.TypeInt, Default: 0},
		{Name: "retry_time", Type: field.TypeInt, Default: 0},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "best_result_time", Type: field.TypeInt, Default: 0},
		{Name: "best_retry_count", Type: field.TypeInt, Default: 0},
		{Name: "best_match_time", Type: field.TypeInt, Default: 0},
		{Name: "worst_result_time", Type: field.TypeInt, Default: 0},
		{Name: "worst_retry_count", Type: field.TypeInt, Default: 0},
		{Name: "worst_match_time", Type: field.TypeInt, Default: 0},
		{Name: "max_win_streak", Type: field.TypeInt, Default: 0},
		{Name: "max_lose_streak", Type: field.TypeInt, Default: 0},
		{Name: "max_login_streak", Type: field.TypeInt, Default: 0},
		{Name: "search_score", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
	}
	// StatisticsTable holds the schema information for the "statistics" table.
	StatisticsTable = &schema.Table{
		Name:       "statistics",
		Columns:    StatisticsColumns,
		PrimaryKey: []*schema.Column{StatisticsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "statistics_users_statistics",
				Columns:    []*schema.Column{StatisticsColumns[22]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "lower_username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "password", Type: field.TypeString},
		{Name: "hardware_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "access_level", Type: field.TypeString},
		{Name: "genshin_uid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "hoyolab_login", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "invites_enabled", Type: field.TypeBool, Default: false},
		{Name: "login_at", Type: field.TypeTime},
		{Name: "login_streak", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "search_blocked_until", Type: field.TypeTime, Nullable: true},
		{Name: "account_blocked_until", Type: field.TypeTime, Nullable: true},
		{Name: "current_item_in_profile_id", Type: field.TypeInt, Nullable: true},
		{Name: "current_match_id", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_user_items_current_item",
				Columns:    []*schema.Column{UsersColumns[16]},
				RefColumns: []*schema.Column{UserItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "users_matches_current_match",
				Columns:    []*schema.Column{UsersColumns[17]},
				RefColumns: []*schema.Column{MatchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserItemsColumns holds the columns for the "user_items" table.
	UserItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "received_from_id", Type: field.TypeInt, Default: 0},
		{Name: "obtained_at", Type: field.TypeTime},
		{Name: "item_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// UserItemsTable holds the schema information for the "user_items" table.
	UserItemsTable = &schema.Table{
		Name:       "user_items",
		Columns:    UserItemsColumns,
		PrimaryKey: []*schema.Column{UserItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_items_game_items_user_items",
				Columns:    []*schema.Column{UserItemsColumns[3]},
				RefColumns: []*schema.Column{GameItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_items_users_items",
				Columns:    []*schema.Column{UserItemsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useritem_item_id",
				Unique:  true,
				Columns: []*schema.Column{UserItemsColumns[3]},
			},
			{
				Name:    "useritem_user_id",
				Unique:  true,
				Columns: []*schema.Column{UserItemsColumns[4]},
			},
		},
	}
	// UserFriendsColumns holds the columns for the "user_friends" table.
	UserFriendsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "friend_id", Type: field.TypeInt},
	}
	// UserFriendsTable holds the schema information for the "user_friends" table.
	UserFriendsTable = &schema.Table{
		Name:       "user_friends",
		Columns:    UserFriendsColumns,
		PrimaryKey: []*schema.Column{UserFriendsColumns[0], UserFriendsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_friends_user_id",
				Columns:    []*schema.Column{UserFriendsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_friends_friend_id",
				Columns:    []*schema.Column{UserFriendsColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FriendRequestsTable,
		GameItemsTable,
		MatchesTable,
		MatchResultsTable,
		StatisticsTable,
		UsersTable,
		UserItemsTable,
		UserFriendsTable,
	}
)

func init() {
	FriendRequestsTable.ForeignKeys[0].RefTable = UsersTable
	FriendRequestsTable.ForeignKeys[1].RefTable = UsersTable
	MatchesTable.ForeignKeys[0].RefTable = UsersTable
	MatchesTable.ForeignKeys[1].RefTable = UsersTable
	MatchResultsTable.ForeignKeys[0].RefTable = MatchesTable
	MatchResultsTable.ForeignKeys[1].RefTable = UsersTable
	StatisticsTable.ForeignKeys[0].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = UserItemsTable
	UsersTable.ForeignKeys[1].RefTable = MatchesTable
	UserItemsTable.ForeignKeys[0].RefTable = GameItemsTable
	UserItemsTable.ForeignKeys[1].RefTable = UsersTable
	UserFriendsTable.ForeignKeys[0].RefTable = UsersTable
	UserFriendsTable.ForeignKeys[1].RefTable = UsersTable
}
