// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FriendRequest is the predicate function for friendrequest builders.
type FriendRequest func(*sql.Selector)

// GameItem is the predicate function for gameitem builders.
type GameItem func(*sql.Selector)

// InventoryItem is the predicate function for inventoryitem builders.
type InventoryItem func(*sql.Selector)

// Match is the predicate function for match builders.
type Match func(*sql.Selector)

// MatchResult is the predicate function for matchresult builders.
type MatchResult func(*sql.Selector)

// Statistic is the predicate function for statistic builders.
type Statistic func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserBalance is the predicate function for userbalance builders.
type UserBalance func(*sql.Selector)
