version: "2"

linters:
  default: all

  disable:
    - wrapcheck
    - ireturn # ???
    - nonamedreturns
    - gochecknoinits # not configurable (swaggo docs must be excluded)
    - gochecknoglobals # not configurable (swaggo docs, custom errors and validator must be excluded)
    - errname # not configurable (canonical custom http-like errors must be excluded)
    - depguard
    - testpackage
    - exhaustruct # freakin linter that argue with mu, wg, ...
    # Must be turned on after
    - revive

  settings:
    gomoddirectives:
      replace-local: true

    funlen:
      lines: 90

    cyclop:
      max-complexity: 15

    recvcheck:
      exclusions:
        - "*.Value"
        - "*.Scan"

    tagalign:
      sort: true

      order:
        - json
        - yaml
        - yml
        - toml
        - mapstructure
        - binding
        - validate
        # Tag for swaggo (ordered after json and validate, because if an example exists,
        # json and validate also exist (if validations exist in principle))
        - example

    tagliatelle:
      case:
        rules:
          json: snake

    varnamelen:
      ignore-decls:
        - c *fiber.Ctx
        - T any
        - w http.ResponseWriter
        - w io.WriteCloser
        - r *http.Request
        - t testing.T
        - wg sync.WaitGroup
        - tx *ent.Tx
        - ch chan

      ignore-names:
        - id  # any identification
        - ok # boolean value
        - fn # func
        - tt # test
        - tc # test case
        - dp # dependency provider

      ignore-type-assert-ok: true
      ignore-map-index-ok: true


  exclusions:
    rules:
      - path: docs/docs.go # autogenerated by swaggo/swag
        linters:
          - lll

      - path: internal/common/errors # custom application errors
        linters:
          - err113

      - path: internal/domain/entity/mailmessage/templates.go # html templates
        linters:
          - lll

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines
