// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/intezya/abyssleague/services/abysscore/internal/infrastructure/ent/friendrequest"
	"github.com/intezya/abyssleague/services/abysscore/internal/infrastructure/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendRequestCreate is the builder for creating a FriendRequest entity.
type FriendRequestCreate struct {
	config
	mutation *FriendRequestMutation
	hooks    []Hook
}

// SetFromUserID sets the "from_user_id" field.
func (frc *FriendRequestCreate) SetFromUserID(i int) *FriendRequestCreate {
	frc.mutation.SetFromUserID(i)
	return frc
}

// SetToUserID sets the "to_user_id" field.
func (frc *FriendRequestCreate) SetToUserID(i int) *FriendRequestCreate {
	frc.mutation.SetToUserID(i)
	return frc
}

// SetCreatedAt sets the "created_at" field.
func (frc *FriendRequestCreate) SetCreatedAt(t time.Time) *FriendRequestCreate {
	frc.mutation.SetCreatedAt(t)
	return frc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (frc *FriendRequestCreate) SetNillableCreatedAt(t *time.Time) *FriendRequestCreate {
	if t != nil {
		frc.SetCreatedAt(*t)
	}
	return frc
}

// SetID sets the "id" field.
func (frc *FriendRequestCreate) SetID(i int) *FriendRequestCreate {
	frc.mutation.SetID(i)
	return frc
}

// SetFromUser sets the "from_user" edge to the User entity.
func (frc *FriendRequestCreate) SetFromUser(u *User) *FriendRequestCreate {
	return frc.SetFromUserID(u.ID)
}

// SetToUser sets the "to_user" edge to the User entity.
func (frc *FriendRequestCreate) SetToUser(u *User) *FriendRequestCreate {
	return frc.SetToUserID(u.ID)
}

// Mutation returns the FriendRequestMutation object of the builder.
func (frc *FriendRequestCreate) Mutation() *FriendRequestMutation {
	return frc.mutation
}

// Save creates the FriendRequest in the database.
func (frc *FriendRequestCreate) Save(ctx context.Context) (*FriendRequest, error) {
	frc.defaults()
	return withHooks(ctx, frc.sqlSave, frc.mutation, frc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (frc *FriendRequestCreate) SaveX(ctx context.Context) *FriendRequest {
	v, err := frc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frc *FriendRequestCreate) Exec(ctx context.Context) error {
	_, err := frc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frc *FriendRequestCreate) ExecX(ctx context.Context) {
	if err := frc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (frc *FriendRequestCreate) defaults() {
	if _, ok := frc.mutation.CreatedAt(); !ok {
		v := friendrequest.DefaultCreatedAt()
		frc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (frc *FriendRequestCreate) check() error {
	if _, ok := frc.mutation.FromUserID(); !ok {
		return &ValidationError{Name: "from_user_id", err: errors.New(`ent: missing required field "FriendRequest.from_user_id"`)}
	}
	if _, ok := frc.mutation.ToUserID(); !ok {
		return &ValidationError{Name: "to_user_id", err: errors.New(`ent: missing required field "FriendRequest.to_user_id"`)}
	}
	if _, ok := frc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FriendRequest.created_at"`)}
	}
	if len(frc.mutation.FromUserIDs()) == 0 {
		return &ValidationError{Name: "from_user", err: errors.New(`ent: missing required edge "FriendRequest.from_user"`)}
	}
	if len(frc.mutation.ToUserIDs()) == 0 {
		return &ValidationError{Name: "to_user", err: errors.New(`ent: missing required edge "FriendRequest.to_user"`)}
	}
	return nil
}

func (frc *FriendRequestCreate) sqlSave(ctx context.Context) (*FriendRequest, error) {
	if err := frc.check(); err != nil {
		return nil, err
	}
	_node, _spec := frc.createSpec()
	if err := sqlgraph.CreateNode(ctx, frc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	frc.mutation.id = &_node.ID
	frc.mutation.done = true
	return _node, nil
}

func (frc *FriendRequestCreate) createSpec() (*FriendRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &FriendRequest{config: frc.config}
		_spec = sqlgraph.NewCreateSpec(friendrequest.Table, sqlgraph.NewFieldSpec(friendrequest.FieldID, field.TypeInt))
	)
	if id, ok := frc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := frc.mutation.CreatedAt(); ok {
		_spec.SetField(friendrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := frc.mutation.FromUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.FromUserTable,
			Columns: []string{friendrequest.FromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FromUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := frc.mutation.ToUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.ToUserTable,
			Columns: []string{friendrequest.ToUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ToUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FriendRequestCreateBulk is the builder for creating many FriendRequest entities in bulk.
type FriendRequestCreateBulk struct {
	config
	err      error
	builders []*FriendRequestCreate
}

// Save creates the FriendRequest entities in the database.
func (frcb *FriendRequestCreateBulk) Save(ctx context.Context) ([]*FriendRequest, error) {
	if frcb.err != nil {
		return nil, frcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(frcb.builders))
	nodes := make([]*FriendRequest, len(frcb.builders))
	mutators := make([]Mutator, len(frcb.builders))
	for i := range frcb.builders {
		func(i int, root context.Context) {
			builder := frcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FriendRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, frcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, frcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, frcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (frcb *FriendRequestCreateBulk) SaveX(ctx context.Context) []*FriendRequest {
	v, err := frcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frcb *FriendRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := frcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frcb *FriendRequestCreateBulk) ExecX(ctx context.Context) {
	if err := frcb.Exec(ctx); err != nil {
		panic(err)
	}
}
