// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/intezya/abyssleague/services/abysscore/internal/infrastructure/ent/gameitem"
	"github.com/intezya/abyssleague/services/abysscore/internal/infrastructure/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameItemDelete is the builder for deleting a GameItem entity.
type GameItemDelete struct {
	config
	hooks    []Hook
	mutation *GameItemMutation
}

// Where appends a list predicates to the GameItemDelete builder.
func (gid *GameItemDelete) Where(ps ...predicate.GameItem) *GameItemDelete {
	gid.mutation.Where(ps...)
	return gid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gid *GameItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gid.sqlExec, gid.mutation, gid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gid *GameItemDelete) ExecX(ctx context.Context) int {
	n, err := gid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gid *GameItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gameitem.Table, sqlgraph.NewFieldSpec(gameitem.FieldID, field.TypeInt))
	if ps := gid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gid.mutation.done = true
	return affected, err
}

// GameItemDeleteOne is the builder for deleting a single GameItem entity.
type GameItemDeleteOne struct {
	gid *GameItemDelete
}

// Where appends a list predicates to the GameItemDelete builder.
func (gido *GameItemDeleteOne) Where(ps ...predicate.GameItem) *GameItemDeleteOne {
	gido.gid.mutation.Where(ps...)
	return gido
}

// Exec executes the deletion query.
func (gido *GameItemDeleteOne) Exec(ctx context.Context) error {
	n, err := gido.gid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gameitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gido *GameItemDeleteOne) ExecX(ctx context.Context) {
	if err := gido.Exec(ctx); err != nil {
		panic(err)
	}
}
