// Code generated by ent, DO NOT EDIT.

package ent

import (
	"abysscore/internal/infrastructure/ent/gameitem"
	"abysscore/internal/infrastructure/ent/inventoryitem"
	"abysscore/internal/infrastructure/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InventoryItemCreate is the builder for creating a InventoryItem entity.
type InventoryItemCreate struct {
	config
	mutation *InventoryItemMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (iic *InventoryItemCreate) SetUserID(i int) *InventoryItemCreate {
	iic.mutation.SetUserID(i)
	return iic
}

// SetItemID sets the "item_id" field.
func (iic *InventoryItemCreate) SetItemID(i int) *InventoryItemCreate {
	iic.mutation.SetItemID(i)
	return iic
}

// SetReceivedFromID sets the "received_from_id" field.
func (iic *InventoryItemCreate) SetReceivedFromID(i int) *InventoryItemCreate {
	iic.mutation.SetReceivedFromID(i)
	return iic
}

// SetNillableReceivedFromID sets the "received_from_id" field if the given value is not nil.
func (iic *InventoryItemCreate) SetNillableReceivedFromID(i *int) *InventoryItemCreate {
	if i != nil {
		iic.SetReceivedFromID(*i)
	}
	return iic
}

// SetObtainedAt sets the "obtained_at" field.
func (iic *InventoryItemCreate) SetObtainedAt(t time.Time) *InventoryItemCreate {
	iic.mutation.SetObtainedAt(t)
	return iic
}

// SetNillableObtainedAt sets the "obtained_at" field if the given value is not nil.
func (iic *InventoryItemCreate) SetNillableObtainedAt(t *time.Time) *InventoryItemCreate {
	if t != nil {
		iic.SetObtainedAt(*t)
	}
	return iic
}

// SetID sets the "id" field.
func (iic *InventoryItemCreate) SetID(i int) *InventoryItemCreate {
	iic.mutation.SetID(i)
	return iic
}

// SetUser sets the "user" edge to the User entity.
func (iic *InventoryItemCreate) SetUser(u *User) *InventoryItemCreate {
	return iic.SetUserID(u.ID)
}

// SetItem sets the "item" edge to the GameItem entity.
func (iic *InventoryItemCreate) SetItem(g *GameItem) *InventoryItemCreate {
	return iic.SetItemID(g.ID)
}

// Mutation returns the InventoryItemMutation object of the builder.
func (iic *InventoryItemCreate) Mutation() *InventoryItemMutation {
	return iic.mutation
}

// Save creates the InventoryItem in the database.
func (iic *InventoryItemCreate) Save(ctx context.Context) (*InventoryItem, error) {
	iic.defaults()
	return withHooks(ctx, iic.sqlSave, iic.mutation, iic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (iic *InventoryItemCreate) SaveX(ctx context.Context) *InventoryItem {
	v, err := iic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iic *InventoryItemCreate) Exec(ctx context.Context) error {
	_, err := iic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iic *InventoryItemCreate) ExecX(ctx context.Context) {
	if err := iic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iic *InventoryItemCreate) defaults() {
	if _, ok := iic.mutation.ReceivedFromID(); !ok {
		v := inventoryitem.DefaultReceivedFromID
		iic.mutation.SetReceivedFromID(v)
	}
	if _, ok := iic.mutation.ObtainedAt(); !ok {
		v := inventoryitem.DefaultObtainedAt()
		iic.mutation.SetObtainedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iic *InventoryItemCreate) check() error {
	if _, ok := iic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InventoryItem.user_id"`)}
	}
	if _, ok := iic.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "InventoryItem.item_id"`)}
	}
	if _, ok := iic.mutation.ReceivedFromID(); !ok {
		return &ValidationError{Name: "received_from_id", err: errors.New(`ent: missing required field "InventoryItem.received_from_id"`)}
	}
	if v, ok := iic.mutation.ReceivedFromID(); ok {
		if err := inventoryitem.ReceivedFromIDValidator(v); err != nil {
			return &ValidationError{Name: "received_from_id", err: fmt.Errorf(`ent: validator failed for field "InventoryItem.received_from_id": %w`, err)}
		}
	}
	if _, ok := iic.mutation.ObtainedAt(); !ok {
		return &ValidationError{Name: "obtained_at", err: errors.New(`ent: missing required field "InventoryItem.obtained_at"`)}
	}
	if len(iic.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InventoryItem.user"`)}
	}
	if len(iic.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "InventoryItem.item"`)}
	}
	return nil
}

func (iic *InventoryItemCreate) sqlSave(ctx context.Context) (*InventoryItem, error) {
	if err := iic.check(); err != nil {
		return nil, err
	}
	_node, _spec := iic.createSpec()
	if err := sqlgraph.CreateNode(ctx, iic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	iic.mutation.id = &_node.ID
	iic.mutation.done = true
	return _node, nil
}

func (iic *InventoryItemCreate) createSpec() (*InventoryItem, *sqlgraph.CreateSpec) {
	var (
		_node = &InventoryItem{config: iic.config}
		_spec = sqlgraph.NewCreateSpec(inventoryitem.Table, sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt))
	)
	if id, ok := iic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := iic.mutation.ReceivedFromID(); ok {
		_spec.SetField(inventoryitem.FieldReceivedFromID, field.TypeInt, value)
		_node.ReceivedFromID = &value
	}
	if value, ok := iic.mutation.ObtainedAt(); ok {
		_spec.SetField(inventoryitem.FieldObtainedAt, field.TypeTime, value)
		_node.ObtainedAt = value
	}
	if nodes := iic.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventoryitem.UserTable,
			Columns: []string{inventoryitem.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := iic.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventoryitem.ItemTable,
			Columns: []string{inventoryitem.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InventoryItemCreateBulk is the builder for creating many InventoryItem entities in bulk.
type InventoryItemCreateBulk struct {
	config
	err      error
	builders []*InventoryItemCreate
}

// Save creates the InventoryItem entities in the database.
func (iicb *InventoryItemCreateBulk) Save(ctx context.Context) ([]*InventoryItem, error) {
	if iicb.err != nil {
		return nil, iicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iicb.builders))
	nodes := make([]*InventoryItem, len(iicb.builders))
	mutators := make([]Mutator, len(iicb.builders))
	for i := range iicb.builders {
		func(i int, root context.Context) {
			builder := iicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iicb *InventoryItemCreateBulk) SaveX(ctx context.Context) []*InventoryItem {
	v, err := iicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iicb *InventoryItemCreateBulk) Exec(ctx context.Context) error {
	_, err := iicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iicb *InventoryItemCreateBulk) ExecX(ctx context.Context) {
	if err := iicb.Exec(ctx); err != nil {
		panic(err)
	}
}
