// Code generated by ent, DO NOT EDIT.

package ent

import (
	"abysscore/internal/infrastructure/ent/match"
	"abysscore/internal/infrastructure/ent/playermatchresult"
	"abysscore/internal/infrastructure/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PlayerMatchResult is the model entity for the PlayerMatchResult schema.
type PlayerMatchResult struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MatchID holds the value of the "match_id" field.
	MatchID int `json:"match_id,omitempty"`
	// PlayerID holds the value of the "player_id" field.
	PlayerID int `json:"player_id,omitempty"`
	// lower is better: 0 is best, 600 is worst
	Score int `json:"score,omitempty"`
	// IsRetried holds the value of the "is_retried" field.
	IsRetried bool `json:"is_retried,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlayerMatchResultQuery when eager-loading is set.
	Edges        PlayerMatchResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlayerMatchResultEdges holds the relations/edges for other nodes in the graph.
type PlayerMatchResultEdges struct {
	// Match holds the value of the match edge.
	Match *Match `json:"match,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MatchOrErr returns the Match value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerMatchResultEdges) MatchOrErr() (*Match, error) {
	if e.Match != nil {
		return e.Match, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: match.Label}
	}
	return nil, &NotLoadedError{edge: "match"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerMatchResultEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayerMatchResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playermatchresult.FieldIsRetried:
			values[i] = new(sql.NullBool)
		case playermatchresult.FieldID, playermatchresult.FieldMatchID, playermatchresult.FieldPlayerID, playermatchresult.FieldScore:
			values[i] = new(sql.NullInt64)
		case playermatchresult.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayerMatchResult fields.
func (pmr *PlayerMatchResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playermatchresult.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pmr.ID = int(value.Int64)
		case playermatchresult.FieldMatchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field match_id", values[i])
			} else if value.Valid {
				pmr.MatchID = int(value.Int64)
			}
		case playermatchresult.FieldPlayerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field player_id", values[i])
			} else if value.Valid {
				pmr.PlayerID = int(value.Int64)
			}
		case playermatchresult.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				pmr.Score = int(value.Int64)
			}
		case playermatchresult.FieldIsRetried:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_retried", values[i])
			} else if value.Valid {
				pmr.IsRetried = value.Bool
			}
		case playermatchresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pmr.CreatedAt = value.Time
			}
		default:
			pmr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayerMatchResult.
// This includes values selected through modifiers, order, etc.
func (pmr *PlayerMatchResult) Value(name string) (ent.Value, error) {
	return pmr.selectValues.Get(name)
}

// QueryMatch queries the "match" edge of the PlayerMatchResult entity.
func (pmr *PlayerMatchResult) QueryMatch() *MatchQuery {
	return NewPlayerMatchResultClient(pmr.config).QueryMatch(pmr)
}

// QueryUser queries the "user" edge of the PlayerMatchResult entity.
func (pmr *PlayerMatchResult) QueryUser() *UserQuery {
	return NewPlayerMatchResultClient(pmr.config).QueryUser(pmr)
}

// Update returns a builder for updating this PlayerMatchResult.
// Note that you need to call PlayerMatchResult.Unwrap() before calling this method if this PlayerMatchResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (pmr *PlayerMatchResult) Update() *PlayerMatchResultUpdateOne {
	return NewPlayerMatchResultClient(pmr.config).UpdateOne(pmr)
}

// Unwrap unwraps the PlayerMatchResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pmr *PlayerMatchResult) Unwrap() *PlayerMatchResult {
	_tx, ok := pmr.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayerMatchResult is not a transactional entity")
	}
	pmr.config.driver = _tx.drv
	return pmr
}

// String implements the fmt.Stringer.
func (pmr *PlayerMatchResult) String() string {
	var builder strings.Builder
	builder.WriteString("PlayerMatchResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pmr.ID))
	builder.WriteString("match_id=")
	builder.WriteString(fmt.Sprintf("%v", pmr.MatchID))
	builder.WriteString(", ")
	builder.WriteString("player_id=")
	builder.WriteString(fmt.Sprintf("%v", pmr.PlayerID))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", pmr.Score))
	builder.WriteString(", ")
	builder.WriteString("is_retried=")
	builder.WriteString(fmt.Sprintf("%v", pmr.IsRetried))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pmr.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlayerMatchResults is a parsable slice of PlayerMatchResult.
type PlayerMatchResults []*PlayerMatchResult
