// Code generated by ent, DO NOT EDIT.

package ent

import (
	"abysscore/internal/infrastructure/ent/friendrequest"
	"abysscore/internal/infrastructure/ent/gameitem"
	"abysscore/internal/infrastructure/ent/inventoryitem"
	"abysscore/internal/infrastructure/ent/match"
	"abysscore/internal/infrastructure/ent/matchresult"
	"abysscore/internal/infrastructure/ent/schema"
	"abysscore/internal/infrastructure/ent/schema/access_level"
	"abysscore/internal/infrastructure/ent/statistic"
	"abysscore/internal/infrastructure/ent/user"
	"abysscore/internal/infrastructure/ent/userbalance"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	friendrequestFields := schema.FriendRequest{}.Fields()
	_ = friendrequestFields
	// friendrequestDescCreatedAt is the schema descriptor for created_at field.
	friendrequestDescCreatedAt := friendrequestFields[3].Descriptor()
	// friendrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	friendrequest.DefaultCreatedAt = friendrequestDescCreatedAt.Default.(func() time.Time)
	gameitemFields := schema.GameItem{}.Fields()
	_ = gameitemFields
	// gameitemDescName is the schema descriptor for name field.
	gameitemDescName := gameitemFields[1].Descriptor()
	// gameitem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gameitem.NameValidator = gameitemDescName.Validators[0].(func(string) error)
	// gameitemDescCollection is the schema descriptor for collection field.
	gameitemDescCollection := gameitemFields[2].Descriptor()
	// gameitem.CollectionValidator is a validator for the "collection" field. It is called by the builders before save.
	gameitem.CollectionValidator = gameitemDescCollection.Validators[0].(func(string) error)
	// gameitemDescType is the schema descriptor for type field.
	gameitemDescType := gameitemFields[3].Descriptor()
	// gameitem.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	gameitem.TypeValidator = gameitemDescType.Validators[0].(func(int) error)
	// gameitemDescRarity is the schema descriptor for rarity field.
	gameitemDescRarity := gameitemFields[4].Descriptor()
	// gameitem.RarityValidator is a validator for the "rarity" field. It is called by the builders before save.
	gameitem.RarityValidator = gameitemDescRarity.Validators[0].(func(int) error)
	// gameitemDescCreatedAt is the schema descriptor for created_at field.
	gameitemDescCreatedAt := gameitemFields[5].Descriptor()
	// gameitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	gameitem.DefaultCreatedAt = gameitemDescCreatedAt.Default.(func() time.Time)
	inventoryitemFields := schema.InventoryItem{}.Fields()
	_ = inventoryitemFields
	// inventoryitemDescReceivedFromID is the schema descriptor for received_from_id field.
	inventoryitemDescReceivedFromID := inventoryitemFields[3].Descriptor()
	// inventoryitem.DefaultReceivedFromID holds the default value on creation for the received_from_id field.
	inventoryitem.DefaultReceivedFromID = inventoryitemDescReceivedFromID.Default.(int)
	// inventoryitem.ReceivedFromIDValidator is a validator for the "received_from_id" field. It is called by the builders before save.
	inventoryitem.ReceivedFromIDValidator = inventoryitemDescReceivedFromID.Validators[0].(func(int) error)
	// inventoryitemDescObtainedAt is the schema descriptor for obtained_at field.
	inventoryitemDescObtainedAt := inventoryitemFields[4].Descriptor()
	// inventoryitem.DefaultObtainedAt holds the default value on creation for the obtained_at field.
	inventoryitem.DefaultObtainedAt = inventoryitemDescObtainedAt.Default.(func() time.Time)
	matchFields := schema.Match{}.Fields()
	_ = matchFields
	// matchDescPlayer1PenaltyTime is the schema descriptor for player1_penalty_time field.
	matchDescPlayer1PenaltyTime := matchFields[3].Descriptor()
	// match.DefaultPlayer1PenaltyTime holds the default value on creation for the player1_penalty_time field.
	match.DefaultPlayer1PenaltyTime = matchDescPlayer1PenaltyTime.Default.(int)
	// match.Player1PenaltyTimeValidator is a validator for the "player1_penalty_time" field. It is called by the builders before save.
	match.Player1PenaltyTimeValidator = matchDescPlayer1PenaltyTime.Validators[0].(func(int) error)
	// matchDescPlayer2PenaltyTime is the schema descriptor for player2_penalty_time field.
	matchDescPlayer2PenaltyTime := matchFields[4].Descriptor()
	// match.DefaultPlayer2PenaltyTime holds the default value on creation for the player2_penalty_time field.
	match.DefaultPlayer2PenaltyTime = matchDescPlayer2PenaltyTime.Default.(int)
	// match.Player2PenaltyTimeValidator is a validator for the "player2_penalty_time" field. It is called by the builders before save.
	match.Player2PenaltyTimeValidator = matchDescPlayer2PenaltyTime.Validators[0].(func(int) error)
	// matchDescCreatedAt is the schema descriptor for created_at field.
	matchDescCreatedAt := matchFields[7].Descriptor()
	// match.DefaultCreatedAt holds the default value on creation for the created_at field.
	match.DefaultCreatedAt = matchDescCreatedAt.Default.(func() time.Time)
	// matchDescChangedToCurrentStatusAt is the schema descriptor for changed_to_current_status_at field.
	matchDescChangedToCurrentStatusAt := matchFields[8].Descriptor()
	// match.DefaultChangedToCurrentStatusAt holds the default value on creation for the changed_to_current_status_at field.
	match.DefaultChangedToCurrentStatusAt = matchDescChangedToCurrentStatusAt.Default.(func() time.Time)
	matchresultFields := schema.MatchResult{}.Fields()
	_ = matchresultFields
	// matchresultDescMatchID is the schema descriptor for match_id field.
	matchresultDescMatchID := matchresultFields[1].Descriptor()
	// matchresult.MatchIDValidator is a validator for the "match_id" field. It is called by the builders before save.
	matchresult.MatchIDValidator = matchresultDescMatchID.Validators[0].(func(int) error)
	// matchresultDescPlayerID is the schema descriptor for player_id field.
	matchresultDescPlayerID := matchresultFields[2].Descriptor()
	// matchresult.PlayerIDValidator is a validator for the "player_id" field. It is called by the builders before save.
	matchresult.PlayerIDValidator = matchresultDescPlayerID.Validators[0].(func(int) error)
	// matchresultDescValue is the schema descriptor for value field.
	matchresultDescValue := matchresultFields[3].Descriptor()
	// matchresult.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	matchresult.ValueValidator = matchresultDescValue.Validators[0].(func(int) error)
	// matchresultDescIsRetry is the schema descriptor for is_retry field.
	matchresultDescIsRetry := matchresultFields[4].Descriptor()
	// matchresult.DefaultIsRetry holds the default value on creation for the is_retry field.
	matchresult.DefaultIsRetry = matchresultDescIsRetry.Default.(bool)
	// matchresultDescCreatedAt is the schema descriptor for created_at field.
	matchresultDescCreatedAt := matchresultFields[5].Descriptor()
	// matchresult.DefaultCreatedAt holds the default value on creation for the created_at field.
	matchresult.DefaultCreatedAt = matchresultDescCreatedAt.Default.(func() time.Time)
	statisticFields := schema.Statistic{}.Fields()
	_ = statisticFields
	// statisticDescPeriod is the schema descriptor for period field.
	statisticDescPeriod := statisticFields[3].Descriptor()
	// statistic.DefaultPeriod holds the default value on creation for the period field.
	statistic.DefaultPeriod = statisticDescPeriod.Default.(int)
	// statistic.PeriodValidator is a validator for the "period" field. It is called by the builders before save.
	statistic.PeriodValidator = statisticDescPeriod.Validators[0].(func(int) error)
	// statisticDescXp is the schema descriptor for xp field.
	statisticDescXp := statisticFields[4].Descriptor()
	// statistic.DefaultXp holds the default value on creation for the xp field.
	statistic.DefaultXp = statisticDescXp.Default.(int)
	// statistic.XpValidator is a validator for the "xp" field. It is called by the builders before save.
	statistic.XpValidator = statisticDescXp.Validators[0].(func(int) error)
	// statisticDescMatchCount is the schema descriptor for match_count field.
	statisticDescMatchCount := statisticFields[5].Descriptor()
	// statistic.DefaultMatchCount holds the default value on creation for the match_count field.
	statistic.DefaultMatchCount = statisticDescMatchCount.Default.(int)
	// statistic.MatchCountValidator is a validator for the "match_count" field. It is called by the builders before save.
	statistic.MatchCountValidator = statisticDescMatchCount.Validators[0].(func(int) error)
	// statisticDescWinsCount is the schema descriptor for wins_count field.
	statisticDescWinsCount := statisticFields[6].Descriptor()
	// statistic.DefaultWinsCount holds the default value on creation for the wins_count field.
	statistic.DefaultWinsCount = statisticDescWinsCount.Default.(int)
	// statistic.WinsCountValidator is a validator for the "wins_count" field. It is called by the builders before save.
	statistic.WinsCountValidator = statisticDescWinsCount.Validators[0].(func(int) error)
	// statisticDescLosesCount is the schema descriptor for loses_count field.
	statisticDescLosesCount := statisticFields[7].Descriptor()
	// statistic.DefaultLosesCount holds the default value on creation for the loses_count field.
	statistic.DefaultLosesCount = statisticDescLosesCount.Default.(int)
	// statistic.LosesCountValidator is a validator for the "loses_count" field. It is called by the builders before save.
	statistic.LosesCountValidator = statisticDescLosesCount.Validators[0].(func(int) error)
	// statisticDescDrawsCount is the schema descriptor for draws_count field.
	statisticDescDrawsCount := statisticFields[8].Descriptor()
	// statistic.DefaultDrawsCount holds the default value on creation for the draws_count field.
	statistic.DefaultDrawsCount = statisticDescDrawsCount.Default.(int)
	// statistic.DrawsCountValidator is a validator for the "draws_count" field. It is called by the builders before save.
	statistic.DrawsCountValidator = statisticDescDrawsCount.Validators[0].(func(int) error)
	// statisticDescResultTime is the schema descriptor for result_time field.
	statisticDescResultTime := statisticFields[9].Descriptor()
	// statistic.DefaultResultTime holds the default value on creation for the result_time field.
	statistic.DefaultResultTime = statisticDescResultTime.Default.(int)
	// statistic.ResultTimeValidator is a validator for the "result_time" field. It is called by the builders before save.
	statistic.ResultTimeValidator = statisticDescResultTime.Validators[0].(func(int) error)
	// statisticDescRetryTime is the schema descriptor for retry_time field.
	statisticDescRetryTime := statisticFields[10].Descriptor()
	// statistic.DefaultRetryTime holds the default value on creation for the retry_time field.
	statistic.DefaultRetryTime = statisticDescRetryTime.Default.(int)
	// statistic.RetryTimeValidator is a validator for the "retry_time" field. It is called by the builders before save.
	statistic.RetryTimeValidator = statisticDescRetryTime.Validators[0].(func(int) error)
	// statisticDescRetryCount is the schema descriptor for retry_count field.
	statisticDescRetryCount := statisticFields[11].Descriptor()
	// statistic.DefaultRetryCount holds the default value on creation for the retry_count field.
	statistic.DefaultRetryCount = statisticDescRetryCount.Default.(int)
	// statistic.RetryCountValidator is a validator for the "retry_count" field. It is called by the builders before save.
	statistic.RetryCountValidator = statisticDescRetryCount.Validators[0].(func(int) error)
	// statisticDescBestResultTime is the schema descriptor for best_result_time field.
	statisticDescBestResultTime := statisticFields[12].Descriptor()
	// statistic.DefaultBestResultTime holds the default value on creation for the best_result_time field.
	statistic.DefaultBestResultTime = statisticDescBestResultTime.Default.(int)
	// statistic.BestResultTimeValidator is a validator for the "best_result_time" field. It is called by the builders before save.
	statistic.BestResultTimeValidator = statisticDescBestResultTime.Validators[0].(func(int) error)
	// statisticDescBestRetryCount is the schema descriptor for best_retry_count field.
	statisticDescBestRetryCount := statisticFields[13].Descriptor()
	// statistic.DefaultBestRetryCount holds the default value on creation for the best_retry_count field.
	statistic.DefaultBestRetryCount = statisticDescBestRetryCount.Default.(int)
	// statistic.BestRetryCountValidator is a validator for the "best_retry_count" field. It is called by the builders before save.
	statistic.BestRetryCountValidator = statisticDescBestRetryCount.Validators[0].(func(int) error)
	// statisticDescBestMatchTime is the schema descriptor for best_match_time field.
	statisticDescBestMatchTime := statisticFields[14].Descriptor()
	// statistic.DefaultBestMatchTime holds the default value on creation for the best_match_time field.
	statistic.DefaultBestMatchTime = statisticDescBestMatchTime.Default.(int)
	// statistic.BestMatchTimeValidator is a validator for the "best_match_time" field. It is called by the builders before save.
	statistic.BestMatchTimeValidator = statisticDescBestMatchTime.Validators[0].(func(int) error)
	// statisticDescWorstResultTime is the schema descriptor for worst_result_time field.
	statisticDescWorstResultTime := statisticFields[15].Descriptor()
	// statistic.DefaultWorstResultTime holds the default value on creation for the worst_result_time field.
	statistic.DefaultWorstResultTime = statisticDescWorstResultTime.Default.(int)
	// statistic.WorstResultTimeValidator is a validator for the "worst_result_time" field. It is called by the builders before save.
	statistic.WorstResultTimeValidator = statisticDescWorstResultTime.Validators[0].(func(int) error)
	// statisticDescWorstRetryCount is the schema descriptor for worst_retry_count field.
	statisticDescWorstRetryCount := statisticFields[16].Descriptor()
	// statistic.DefaultWorstRetryCount holds the default value on creation for the worst_retry_count field.
	statistic.DefaultWorstRetryCount = statisticDescWorstRetryCount.Default.(int)
	// statistic.WorstRetryCountValidator is a validator for the "worst_retry_count" field. It is called by the builders before save.
	statistic.WorstRetryCountValidator = statisticDescWorstRetryCount.Validators[0].(func(int) error)
	// statisticDescWorstMatchTime is the schema descriptor for worst_match_time field.
	statisticDescWorstMatchTime := statisticFields[17].Descriptor()
	// statistic.DefaultWorstMatchTime holds the default value on creation for the worst_match_time field.
	statistic.DefaultWorstMatchTime = statisticDescWorstMatchTime.Default.(int)
	// statistic.WorstMatchTimeValidator is a validator for the "worst_match_time" field. It is called by the builders before save.
	statistic.WorstMatchTimeValidator = statisticDescWorstMatchTime.Validators[0].(func(int) error)
	// statisticDescMaxWinStreak is the schema descriptor for max_win_streak field.
	statisticDescMaxWinStreak := statisticFields[18].Descriptor()
	// statistic.DefaultMaxWinStreak holds the default value on creation for the max_win_streak field.
	statistic.DefaultMaxWinStreak = statisticDescMaxWinStreak.Default.(int)
	// statistic.MaxWinStreakValidator is a validator for the "max_win_streak" field. It is called by the builders before save.
	statistic.MaxWinStreakValidator = statisticDescMaxWinStreak.Validators[0].(func(int) error)
	// statisticDescMaxLoseStreak is the schema descriptor for max_lose_streak field.
	statisticDescMaxLoseStreak := statisticFields[19].Descriptor()
	// statistic.DefaultMaxLoseStreak holds the default value on creation for the max_lose_streak field.
	statistic.DefaultMaxLoseStreak = statisticDescMaxLoseStreak.Default.(int)
	// statistic.MaxLoseStreakValidator is a validator for the "max_lose_streak" field. It is called by the builders before save.
	statistic.MaxLoseStreakValidator = statisticDescMaxLoseStreak.Validators[0].(func(int) error)
	// statisticDescMaxLoginStreak is the schema descriptor for max_login_streak field.
	statisticDescMaxLoginStreak := statisticFields[20].Descriptor()
	// statistic.DefaultMaxLoginStreak holds the default value on creation for the max_login_streak field.
	statistic.DefaultMaxLoginStreak = statisticDescMaxLoginStreak.Default.(int)
	// statistic.MaxLoginStreakValidator is a validator for the "max_login_streak" field. It is called by the builders before save.
	statistic.MaxLoginStreakValidator = statisticDescMaxLoginStreak.Validators[0].(func(int) error)
	// statisticDescSearchScore is the schema descriptor for search_score field.
	statisticDescSearchScore := statisticFields[21].Descriptor()
	// statistic.DefaultSearchScore holds the default value on creation for the search_score field.
	statistic.DefaultSearchScore = statisticDescSearchScore.Default.(int)
	// statistic.SearchScoreValidator is a validator for the "search_score" field. It is called by the builders before save.
	statistic.SearchScoreValidator = statisticDescSearchScore.Validators[0].(func(int) error)
	// statisticDescCreatedAt is the schema descriptor for created_at field.
	statisticDescCreatedAt := statisticFields[22].Descriptor()
	// statistic.DefaultCreatedAt holds the default value on creation for the created_at field.
	statistic.DefaultCreatedAt = statisticDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescLowerUsername is the schema descriptor for lower_username field.
	userDescLowerUsername := userFields[2].Descriptor()
	// user.LowerUsernameValidator is a validator for the "lower_username" field. It is called by the builders before save.
	user.LowerUsernameValidator = userDescLowerUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[4].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescAccessLevel is the schema descriptor for access_level field.
	userDescAccessLevel := userFields[6].Descriptor()
	// user.DefaultAccessLevel holds the default value on creation for the access_level field.
	user.DefaultAccessLevel = userDescAccessLevel.Default.(func() access_level.AccessLevel)
	// userDescInvitesEnabled is the schema descriptor for invites_enabled field.
	userDescInvitesEnabled := userFields[12].Descriptor()
	// user.DefaultInvitesEnabled holds the default value on creation for the invites_enabled field.
	user.DefaultInvitesEnabled = userDescInvitesEnabled.Default.(bool)
	// userDescLoginAt is the schema descriptor for login_at field.
	userDescLoginAt := userFields[13].Descriptor()
	// user.DefaultLoginAt holds the default value on creation for the login_at field.
	user.DefaultLoginAt = userDescLoginAt.Default.(func() time.Time)
	// userDescLoginStreak is the schema descriptor for login_streak field.
	userDescLoginStreak := userFields[14].Descriptor()
	// user.DefaultLoginStreak holds the default value on creation for the login_streak field.
	user.DefaultLoginStreak = userDescLoginStreak.Default.(int)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[15].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescSearchBlockedLevel is the schema descriptor for search_blocked_level field.
	userDescSearchBlockedLevel := userFields[18].Descriptor()
	// user.DefaultSearchBlockedLevel holds the default value on creation for the search_blocked_level field.
	user.DefaultSearchBlockedLevel = userDescSearchBlockedLevel.Default.(int)
	// user.SearchBlockedLevelValidator is a validator for the "search_blocked_level" field. It is called by the builders before save.
	user.SearchBlockedLevelValidator = userDescSearchBlockedLevel.Validators[0].(func(int) error)
	// userDescAccountBlockedLevel is the schema descriptor for account_blocked_level field.
	userDescAccountBlockedLevel := userFields[21].Descriptor()
	// user.DefaultAccountBlockedLevel holds the default value on creation for the account_blocked_level field.
	user.DefaultAccountBlockedLevel = userDescAccountBlockedLevel.Default.(int)
	// user.AccountBlockedLevelValidator is a validator for the "account_blocked_level" field. It is called by the builders before save.
	user.AccountBlockedLevelValidator = userDescAccountBlockedLevel.Validators[0].(func(int) error)
	userbalanceFields := schema.UserBalance{}.Fields()
	_ = userbalanceFields
	// userbalanceDescCoins is the schema descriptor for coins field.
	userbalanceDescCoins := userbalanceFields[2].Descriptor()
	// userbalance.DefaultCoins holds the default value on creation for the coins field.
	userbalance.DefaultCoins = userbalanceDescCoins.Default.(float64)
	// userbalanceDescLastUpdated is the schema descriptor for last_updated field.
	userbalanceDescLastUpdated := userbalanceFields[3].Descriptor()
	// userbalance.DefaultLastUpdated holds the default value on creation for the last_updated field.
	userbalance.DefaultLastUpdated = userbalanceDescLastUpdated.Default.(func() time.Time)
	// userbalance.UpdateDefaultLastUpdated holds the default value on update for the last_updated field.
	userbalance.UpdateDefaultLastUpdated = userbalanceDescLastUpdated.UpdateDefault.(func() time.Time)
	// userbalanceDescCreatedAt is the schema descriptor for created_at field.
	userbalanceDescCreatedAt := userbalanceFields[4].Descriptor()
	// userbalance.DefaultCreatedAt holds the default value on creation for the created_at field.
	userbalance.DefaultCreatedAt = userbalanceDescCreatedAt.Default.(func() time.Time)
}
