// Code generated by ent, DO NOT EDIT.

package ent

import (
	"abysscore/internal/infrastructure/ent/predicate"
	"abysscore/internal/infrastructure/ent/user"
	"abysscore/internal/infrastructure/ent/userbalance"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserBalanceQuery is the builder for querying UserBalance entities.
type UserBalanceQuery struct {
	config
	ctx        *QueryContext
	order      []userbalance.OrderOption
	inters     []Interceptor
	predicates []predicate.UserBalance
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserBalanceQuery builder.
func (ubq *UserBalanceQuery) Where(ps ...predicate.UserBalance) *UserBalanceQuery {
	ubq.predicates = append(ubq.predicates, ps...)
	return ubq
}

// Limit the number of records to be returned by this query.
func (ubq *UserBalanceQuery) Limit(limit int) *UserBalanceQuery {
	ubq.ctx.Limit = &limit
	return ubq
}

// Offset to start from.
func (ubq *UserBalanceQuery) Offset(offset int) *UserBalanceQuery {
	ubq.ctx.Offset = &offset
	return ubq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ubq *UserBalanceQuery) Unique(unique bool) *UserBalanceQuery {
	ubq.ctx.Unique = &unique
	return ubq
}

// Order specifies how the records should be ordered.
func (ubq *UserBalanceQuery) Order(o ...userbalance.OrderOption) *UserBalanceQuery {
	ubq.order = append(ubq.order, o...)
	return ubq
}

// QueryUser chains the current query on the "user" edge.
func (ubq *UserBalanceQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ubq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ubq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ubq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userbalance.Table, userbalance.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, userbalance.UserTable, userbalance.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ubq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserBalance entity from the query.
// Returns a *NotFoundError when no UserBalance was found.
func (ubq *UserBalanceQuery) First(ctx context.Context) (*UserBalance, error) {
	nodes, err := ubq.Limit(1).All(setContextOp(ctx, ubq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userbalance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ubq *UserBalanceQuery) FirstX(ctx context.Context) *UserBalance {
	node, err := ubq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserBalance ID from the query.
// Returns a *NotFoundError when no UserBalance ID was found.
func (ubq *UserBalanceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ubq.Limit(1).IDs(setContextOp(ctx, ubq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userbalance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ubq *UserBalanceQuery) FirstIDX(ctx context.Context) int {
	id, err := ubq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserBalance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserBalance entity is found.
// Returns a *NotFoundError when no UserBalance entities are found.
func (ubq *UserBalanceQuery) Only(ctx context.Context) (*UserBalance, error) {
	nodes, err := ubq.Limit(2).All(setContextOp(ctx, ubq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userbalance.Label}
	default:
		return nil, &NotSingularError{userbalance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ubq *UserBalanceQuery) OnlyX(ctx context.Context) *UserBalance {
	node, err := ubq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserBalance ID in the query.
// Returns a *NotSingularError when more than one UserBalance ID is found.
// Returns a *NotFoundError when no entities are found.
func (ubq *UserBalanceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ubq.Limit(2).IDs(setContextOp(ctx, ubq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userbalance.Label}
	default:
		err = &NotSingularError{userbalance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ubq *UserBalanceQuery) OnlyIDX(ctx context.Context) int {
	id, err := ubq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserBalances.
func (ubq *UserBalanceQuery) All(ctx context.Context) ([]*UserBalance, error) {
	ctx = setContextOp(ctx, ubq.ctx, ent.OpQueryAll)
	if err := ubq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserBalance, *UserBalanceQuery]()
	return withInterceptors[[]*UserBalance](ctx, ubq, qr, ubq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ubq *UserBalanceQuery) AllX(ctx context.Context) []*UserBalance {
	nodes, err := ubq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserBalance IDs.
func (ubq *UserBalanceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ubq.ctx.Unique == nil && ubq.path != nil {
		ubq.Unique(true)
	}
	ctx = setContextOp(ctx, ubq.ctx, ent.OpQueryIDs)
	if err = ubq.Select(userbalance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ubq *UserBalanceQuery) IDsX(ctx context.Context) []int {
	ids, err := ubq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ubq *UserBalanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ubq.ctx, ent.OpQueryCount)
	if err := ubq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ubq, querierCount[*UserBalanceQuery](), ubq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ubq *UserBalanceQuery) CountX(ctx context.Context) int {
	count, err := ubq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ubq *UserBalanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ubq.ctx, ent.OpQueryExist)
	switch _, err := ubq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ubq *UserBalanceQuery) ExistX(ctx context.Context) bool {
	exist, err := ubq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserBalanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ubq *UserBalanceQuery) Clone() *UserBalanceQuery {
	if ubq == nil {
		return nil
	}
	return &UserBalanceQuery{
		config:     ubq.config,
		ctx:        ubq.ctx.Clone(),
		order:      append([]userbalance.OrderOption{}, ubq.order...),
		inters:     append([]Interceptor{}, ubq.inters...),
		predicates: append([]predicate.UserBalance{}, ubq.predicates...),
		withUser:   ubq.withUser.Clone(),
		// clone intermediate query.
		sql:  ubq.sql.Clone(),
		path: ubq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ubq *UserBalanceQuery) WithUser(opts ...func(*UserQuery)) *UserBalanceQuery {
	query := (&UserClient{config: ubq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ubq.withUser = query
	return ubq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserBalance.Query().
//		GroupBy(userbalance.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ubq *UserBalanceQuery) GroupBy(field string, fields ...string) *UserBalanceGroupBy {
	ubq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserBalanceGroupBy{build: ubq}
	grbuild.flds = &ubq.ctx.Fields
	grbuild.label = userbalance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserBalance.Query().
//		Select(userbalance.FieldUserID).
//		Scan(ctx, &v)
func (ubq *UserBalanceQuery) Select(fields ...string) *UserBalanceSelect {
	ubq.ctx.Fields = append(ubq.ctx.Fields, fields...)
	sbuild := &UserBalanceSelect{UserBalanceQuery: ubq}
	sbuild.label = userbalance.Label
	sbuild.flds, sbuild.scan = &ubq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserBalanceSelect configured with the given aggregations.
func (ubq *UserBalanceQuery) Aggregate(fns ...AggregateFunc) *UserBalanceSelect {
	return ubq.Select().Aggregate(fns...)
}

func (ubq *UserBalanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ubq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ubq); err != nil {
				return err
			}
		}
	}
	for _, f := range ubq.ctx.Fields {
		if !userbalance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ubq.path != nil {
		prev, err := ubq.path(ctx)
		if err != nil {
			return err
		}
		ubq.sql = prev
	}
	return nil
}

func (ubq *UserBalanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserBalance, error) {
	var (
		nodes       = []*UserBalance{}
		_spec       = ubq.querySpec()
		loadedTypes = [1]bool{
			ubq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserBalance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserBalance{config: ubq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ubq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ubq.withUser; query != nil {
		if err := ubq.loadUser(ctx, query, nodes, nil,
			func(n *UserBalance, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ubq *UserBalanceQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserBalance, init func(*UserBalance), assign func(*UserBalance, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserBalance)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ubq *UserBalanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ubq.querySpec()
	_spec.Node.Columns = ubq.ctx.Fields
	if len(ubq.ctx.Fields) > 0 {
		_spec.Unique = ubq.ctx.Unique != nil && *ubq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ubq.driver, _spec)
}

func (ubq *UserBalanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userbalance.Table, userbalance.Columns, sqlgraph.NewFieldSpec(userbalance.FieldID, field.TypeInt))
	_spec.From = ubq.sql
	if unique := ubq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ubq.path != nil {
		_spec.Unique = true
	}
	if fields := ubq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbalance.FieldID)
		for i := range fields {
			if fields[i] != userbalance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ubq.withUser != nil {
			_spec.Node.AddColumnOnce(userbalance.FieldUserID)
		}
	}
	if ps := ubq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ubq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ubq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ubq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ubq *UserBalanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ubq.driver.Dialect())
	t1 := builder.Table(userbalance.Table)
	columns := ubq.ctx.Fields
	if len(columns) == 0 {
		columns = userbalance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ubq.sql != nil {
		selector = ubq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ubq.ctx.Unique != nil && *ubq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ubq.predicates {
		p(selector)
	}
	for _, p := range ubq.order {
		p(selector)
	}
	if offset := ubq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ubq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserBalanceGroupBy is the group-by builder for UserBalance entities.
type UserBalanceGroupBy struct {
	selector
	build *UserBalanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ubgb *UserBalanceGroupBy) Aggregate(fns ...AggregateFunc) *UserBalanceGroupBy {
	ubgb.fns = append(ubgb.fns, fns...)
	return ubgb
}

// Scan applies the selector query and scans the result into the given value.
func (ubgb *UserBalanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ubgb.build.ctx, ent.OpQueryGroupBy)
	if err := ubgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserBalanceQuery, *UserBalanceGroupBy](ctx, ubgb.build, ubgb, ubgb.build.inters, v)
}

func (ubgb *UserBalanceGroupBy) sqlScan(ctx context.Context, root *UserBalanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ubgb.fns))
	for _, fn := range ubgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ubgb.flds)+len(ubgb.fns))
		for _, f := range *ubgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ubgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ubgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserBalanceSelect is the builder for selecting fields of UserBalance entities.
type UserBalanceSelect struct {
	*UserBalanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ubs *UserBalanceSelect) Aggregate(fns ...AggregateFunc) *UserBalanceSelect {
	ubs.fns = append(ubs.fns, fns...)
	return ubs
}

// Scan applies the selector query and scans the result into the given value.
func (ubs *UserBalanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ubs.ctx, ent.OpQuerySelect)
	if err := ubs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserBalanceQuery, *UserBalanceSelect](ctx, ubs.UserBalanceQuery, ubs, ubs.inters, v)
}

func (ubs *UserBalanceSelect) sqlScan(ctx context.Context, root *UserBalanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ubs.fns))
	for _, fn := range ubs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ubs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ubs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
