// Code generated by ent, DO NOT EDIT.

package userbalance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/intezya/abyssleague/services/abysscore/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldUserID, v))
}

// Coins applies equality check predicate on the "coins" field. It's identical to CoinsEQ.
func Coins(v float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldCoins, v))
}

// LastUpdated applies equality check predicate on the "last_updated" field. It's identical to LastUpdatedEQ.
func LastUpdated(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldLastUpdated, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNotIn(FieldUserID, vs...))
}

// CoinsEQ applies the EQ predicate on the "coins" field.
func CoinsEQ(v float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldCoins, v))
}

// CoinsNEQ applies the NEQ predicate on the "coins" field.
func CoinsNEQ(v float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNEQ(FieldCoins, v))
}

// CoinsIn applies the In predicate on the "coins" field.
func CoinsIn(vs ...float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldIn(FieldCoins, vs...))
}

// CoinsNotIn applies the NotIn predicate on the "coins" field.
func CoinsNotIn(vs ...float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNotIn(FieldCoins, vs...))
}

// CoinsGT applies the GT predicate on the "coins" field.
func CoinsGT(v float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGT(FieldCoins, v))
}

// CoinsGTE applies the GTE predicate on the "coins" field.
func CoinsGTE(v float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGTE(FieldCoins, v))
}

// CoinsLT applies the LT predicate on the "coins" field.
func CoinsLT(v float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLT(FieldCoins, v))
}

// CoinsLTE applies the LTE predicate on the "coins" field.
func CoinsLTE(v float64) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLTE(FieldCoins, v))
}

// LastUpdatedEQ applies the EQ predicate on the "last_updated" field.
func LastUpdatedEQ(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldLastUpdated, v))
}

// LastUpdatedNEQ applies the NEQ predicate on the "last_updated" field.
func LastUpdatedNEQ(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNEQ(FieldLastUpdated, v))
}

// LastUpdatedIn applies the In predicate on the "last_updated" field.
func LastUpdatedIn(vs ...time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldIn(FieldLastUpdated, vs...))
}

// LastUpdatedNotIn applies the NotIn predicate on the "last_updated" field.
func LastUpdatedNotIn(vs ...time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNotIn(FieldLastUpdated, vs...))
}

// LastUpdatedGT applies the GT predicate on the "last_updated" field.
func LastUpdatedGT(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGT(FieldLastUpdated, v))
}

// LastUpdatedGTE applies the GTE predicate on the "last_updated" field.
func LastUpdatedGTE(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGTE(FieldLastUpdated, v))
}

// LastUpdatedLT applies the LT predicate on the "last_updated" field.
func LastUpdatedLT(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLT(FieldLastUpdated, v))
}

// LastUpdatedLTE applies the LTE predicate on the "last_updated" field.
func LastUpdatedLTE(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLTE(FieldLastUpdated, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserBalance {
	return predicate.UserBalance(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserBalance {
	return predicate.UserBalance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserBalance {
	return predicate.UserBalance(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserBalance) predicate.UserBalance {
	return predicate.UserBalance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserBalance) predicate.UserBalance {
	return predicate.UserBalance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserBalance) predicate.UserBalance {
	return predicate.UserBalance(sql.NotPredicates(p))
}
